use_frameworks!

platform :ios, '9.0'

target 'UtilityLib_Example' do
  pod 'UtilityLib', :path => '../'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AFNetworking', '~> 4.0'

  target 'UtilityLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
